export const events = [
    {
        title: "Google I/O 2026",
        image: "/images/event1.png",
        slug: "google-io-2026",
        location: "Shoreline Amphitheatre, Mountain View, CA",
        date: "May 19, 2026",
        time: "9:00 AM PT",
    },
    {
        title: "Microsoft Build 2026",
        image: "/images/event2.png",
        slug: "microsoft-build-2026",
        location: "Seattle Convention Center, Seattle, WA",
        date: "May 26, 2026",
        time: "8:30 AM PT",
    },
    {
        title: "AWS re:Invent 2026",
        image: "/images/event3.png",
        slug: "aws-reinvent-2026",
        location: "The Venetian, Las Vegas, NV",
        date: "November 30, 2026",
        time: "10:00 AM PT",
    },
    {
        title: "KubeCon + CloudNativeCon North America 2026",
        image: "/images/event4.png",
        slug: "kubecon-cloudnativecon-na-2026",
        location: "San Diego Convention Center, San Diego, CA",
        date: "October 13, 2026",
        time: "9:00 AM PT",
    },
    {
        title: "TechCrunch Disrupt 2026",
        image: "/images/event5.png",
        slug: "techcrunch-disrupt-2026",
        location: "Moscone West, San Francisco, CA",
        date: "September 22, 2026",
        time: "10:00 AM PT",
    },
    {
        title: "ETHGlobal New York 2026",
        image: "/images/event6.png",
        slug: "ethglobal-new-york-2026",
        location: "Brooklyn Expo Center, New York, NY",
        date: "August 14, 2026",
        time: "11:00 AM ET",
    },
    {
        title: "DevOpsDays London 2026",
        image: "/images/event-full.png",
        slug: "devopsdays-london-2026",
        location: "QEII Centre, London, UK",
        date: "June 11, 2026",
        time: "9:30 AM BST",
    },
] as const;
